### ISSUE TITLE
Poor sliding performance

### ISSUE THREAD

**Issue by robertpiosik** [woofers/react-sheet-slide#12]
Hi, I really appreciate your work on this. Works quite nice although I notice slugginess on less performant devices. "React spring bottom sheet" works a lot better so something is off.

To quickly reproduce, please set CPU throttling in performance tab of chrome dev tools to 20x slowdown.

Thank you for looking into it

**Comment by woofers** [comment]
Hi @robertpiosik, I tried the reproduction and I'm not sure its representative of a real device doing a 20x CPU slowdown as both this library and `react-spring-bottom-sheet` are very unresponsive.  This library also uses a newer version of `react-spring` and `@use-gesture/react` which could affect performance adversely and is not within the scope of this library.

The aim of this library is to provide a iOS-like sheet implementation and it does this at the cost of some performance.  I welcome any contributions to work on this issue but for now I'm closing as a won't fix.

-----

If supporting low-end devices is a requirement for you, I'd recommend checking out Vaul: https://vaul.emilkowal.ski/ which is a fantastic library and does not require an animation library like `react-spring`

**Comment by robertpiosik** [comment]
> as both this library and react-spring-bottom-sheet are very unresponsive

I'm sorry I didn't give exact example I test on. Here is what I compare to: https://react-spring.bottom-sheet.dev/fixtures/simple
I don't understand why the other library is very unresponsive on your end. Could you share your machine's specs? Could you visit `chrome://gpu` and check if your browser supports hardware acceleration? Maybe selecting 8x slowdown will work better for you? At my end 20x lags as hell and practically not at all with the other lib.
