### ISSUE TITLE
Hide Footer?

### ISSUE THREAD

**Issue by rsimon** [woofers/react-sheet-slide#15]
I want to hide the footer from the sheet.

Even though my `<Sheet>` component doesn't have a `<Footer>` child, the rendered sheet still renders an empty footer `<div>`. See the gray bar in the image below:

<img width="436" alt="Bildschirmfoto 2024-08-21 um 14 23 03" src="https://github.com/user-attachments/assets/aef79806-b81f-449c-9f76-5703f23638b4">

My workaround is to add a Footer element with a custom CSS className, and then add `.footer { display: none }` to my stylesheet. Obviously, it's not a serious issue, because it's easy to work around. But I just thought I'd report it.

**Comment by woofers** [comment]
Hi @rsimon, `react-sheet-slide` strongly encourages the use of a footer to prevent any CTA buttons from overflowing on mobile.  Having said that if you want to hide the footer I would recommend just keeping in the React component structure but doing something like `<Footer className="hide-footer" />` .

Then you can effectively hide it and set it to have 0 height:

```css
.hide-footer {
  background: none;
  padding: 0;
  box-shadow: unset;
}
```

`display: none` may also work but I'm not sure if this would affect any of the drag/touch logic.

**Comment by rsimon** [comment]
Thanks for the quick reply. That works for me!
