### ISSUE TITLE
Override CSS 

### ISSUE THREAD

**Issue by emhuskic** [woofers/react-sheet-slide#18]
Hi, is it possible you open the components: Portal, Content, Header etc. for the CSS to be overriden.
For example, I do not want to have **overflow: hidden** in modal, as I want stuff (such as date picker, for example) to be visible outside of the modal.

**Comment by woofers** [comment]
@emhuskic 

This can be done by adding a custom class name to each of the listed components:

> ## Styling

> You can add `className` props to target the following components.  This can
be useful if you are using something like Tailwind or CSS modules, or if you just want to
provide a constant value to target via CSS.

> - `<Header className="header" />` - Targets the header of the sheet
> -`<Header scrolledClassName="scrolled-header" />` - Targets the header style after it has been scrolled
>- `<Content className="content" />` - Targets the content and scrolling container of the sheet
> - `<Footer className="footer" />` - Targets the footer of the sheet
>- `<Sheet backdropClassName=""backdrop />` - Targets the modal/sheet backdrop that closes on backdrop tap


and then creating the relevant CSS rules:

```css
.header, .scrolled-header, .content, .footer, .backdrop {
  /* Your styles here */
}
```

For the `Portal` component you will need to apply a `className` or inline styles directly to the element you portal to.

**Comment by emhuskic** [comment]
@woofers I don't think you understood my question.
To set the **Sheet** style - I have to set a **ref** to the sheet. 
Also - look at the gymnastics I had to do to allow portal to have overflow: visible, and also to change the **handle** of the slide portal. 
```
    const setRef = (el: HTMLDivElement | null) => {
        if (el) {
            el.style.setProperty(
                '--handle',
                themeMode === 'light' ? '#0608083D' : '#F9F9F93D',
            )
            el.style.background = 'transparent'
            el.style.border = '1px'
            el.style.borderRadius = '24px'
            el.style.overflow = 'visible'
            if (el.children) {
                if (mode === 'modal') {
                    el.style.width = 'fit-content'
                    el.style.minWidth = 'fit-content'
                }
                const sheetElement = Array.from(el.children).filter(child =>
                    child.classList.contains('drawer-modal'),
                )?.[0]

                Array.from(sheetElement.children).forEach(element => {
                    if (element instanceof HTMLDivElement) {
                        element.style.overflow = 'visible'
                    }
                })
            }
        }
    }
```

So I wanted either to not use default styles and set my own, or to send the **Sheet / Portal** className directly, as it is done for the Header, as you mentioned.
