### ISSUE TITLE
Move @react-spring/web@^9 and @use-gesture/react@^10 to direct dependencies

### ISSUE THREAD

**Issue by monolithed** [woofers/react-sheet-slide#19]
It would be great if you could move `@react-spring/web@^9` and `@use-gesture/react@^10` to direct dependencies. This will help avoid issues with accidentally removing these dependencies, as they are not explicitly used in the project code (like in my case). 
This is a backward-compatible change anyway.

**Comment by woofers** [comment]
@monolithed Closing this issue as I believe for most users `react-spring` and `@use-gesture/react`  are a better fit as peer dependencies (even if your specific project does not directly use the dependencies directly).  Your package manager should warn if you attempt to accidentally remove the dependencies,

If needed you could always make a wrapper package that re-exports `react-sheet-slide` with specific versions of React Spring and `@use-gesture` setup.
