### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded in react capacitor ionic

### ISSUE THREAD

**Issue by diegosystem32** [woofers/react-sheet-slide#8]
react-sheet-slide.js?v=28aa102f:5011 Uncaught RangeError: Maximum call stack size exceeded

in react capacitor ionic
![image](https://github.com/woofers/react-sheet-slide/assets/55759320/26459aa7-4e65-4f0b-a53b-2650710ed40a)

`<Portal>
                <Sheet
                  ref={modalStickerRef}
                  open={mStickerOpen}
                  onDismiss={() => setMStickerOpen(false)}
                  onClose={() => {
                    console.log('Component unmounted')
                  }}
                  selectedDetent={detents.large}
                  detents={props => [
                    detents.large(props),
                    detents.fit(props)
                  ]}
                  useDarkMode={false}
                  useModal={false}
                  scrollingExpands={true}
                >
                  <Header className="rss-header" scrolledClassName="rss-header-scrolled">Title</Header>
                  <Content className="rss-content">
                    {mStickerOpen ? <StickerModal sendSticker={sendSticker} ></StickerModal> : <></>}
                  </Content>
                  <Footer className="rss-footer">
                    <button type="button" onClick={() => setMStickerOpen(false)}>
                      Close
                    </button>
                  </Footer>
                </Sheet>
              </Portal>
`

**Comment by woofers** [comment]
Hi @diegosystem32, unfortunately there is not enough information in this bug report and the code provided contains elements unrelated to `react-sheet-slide`.  

Going to close this issue for now, but if you continue to run into this issue, please open another with a minimal reproduction provided on either CodeSandbox or a public GitHub repo.  Thanks

**Comment by dmitryshelomanov** [comment]
@woofers its happened when used nested modals
