### ISSUE TITLE
Controlling the speed of drawer animation..?

### ISSUE THREAD

**Issue by artemis-prime** [woofers/react-sheet-slide#9]
How can we control the speed of the drawer animation?  I looked through all the source could and could find where it was happening.  In the spring settings somewhere or ?  Should we expose this is prop or a css var?  Sorry if I'm missing something obvious.  

Thanks for the great work

~A

**Comment by woofers** [comment]
@artemis-prime I have just published `v1.4.0` which now includes a `velocity` prop.  This prop controls the velocity of the spring animation and is defaulted to `1`.  Any value beyond `0.15-6` may make the animation unstable or flicker.  Hope this helps.

**Comment by artemis-prime** [comment]
Thanks!
